-- MySQL Script generated by MySQL Workbench
-- Wed Jan 26 10:00:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clients` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `clients` (
  `idclients` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  `telefon` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`idclients`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proveidors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proveidors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proveidors` (
  `idproveidor` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) CHARACTER SET 'big5' NOT NULL,
  `telefon` INT NOT NULL,
  `fax` INT NULL,
  `NIF` VARCHAR(45) NULL,
  `proveidorscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproveidor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proveidors_has_ulleres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proveidors_has_ulleres` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proveidors_has_ulleres` (
  `proveidors_idproveidor` INT NOT NULL,
  `ulleres_idulleres` INT NOT NULL,
  PRIMARY KEY (`proveidors_idproveidor`, `ulleres_idulleres`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ulleres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ulleres` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ulleres` (
  `idulleres` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `graduacio_dreta` FLOAT NOT NULL,
  `graduacio_esquerra` FLOAT NOT NULL,
  `montura` VARCHAR(45) NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_dret` VARCHAR(45) NOT NULL,
  `color_esquerra` VARCHAR(45) NOT NULL,
  `preu` FLOAT NOT NULL,
  PRIMARY KEY (`idulleres`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
