-- MySQL Script generated by MySQL Workbench
-- Tue Feb  1 09:52:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `botigues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `botigues` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `botigues` (
  `idbotigues` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbotigues`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categories` (
  `idcategories` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategories`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categories_has_comandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories_has_comandes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categories_has_comandes` (
  `categories_idcategories` INT NOT NULL,
  `comandes_idcomandes` INT NOT NULL,
  `comandes_botigues_idbotigues` INT NOT NULL,
  PRIMARY KEY (`categories_idcategories`, `comandes_idcomandes`, `comandes_botigues_idbotigues`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clients` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `clients` (
  `idclients` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `cognaoms` VARCHAR(45) NOT NULL,
  `adreça` VARCHAR(45) NOT NULL,
  `codi_postal` INT NOT NULL,
  `localitat` INT NOT NULL,
  `provincia` INT NOT NULL,
  `telefon` INT NOT NULL,
  `comandes_idcomandes` INT NOT NULL,
  PRIMARY KEY (`idclients`, `comandes_idcomandes`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `comandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comandes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `comandes` (
  `idcomandes` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `domicili_botiga` VARCHAR(45) NOT NULL,
  `quantitat` INT NOT NULL,
  `productes` VARCHAR(45) NOT NULL,
  `preu` FLOAT NOT NULL,
  `botigues_idbotigues` INT NOT NULL,
  PRIMARY KEY (`idcomandes`, `botigues_idbotigues`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `localitats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `localitats` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `localitats` (
  `idlocalitats` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `clients_idclients` INT NOT NULL,
  PRIMARY KEY (`idlocalitats`, `clients_idclients`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `productes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `productes` (
  `idproductes` INT NOT NULL,
  `tipus` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` VARCHAR(200) NOT NULL,
  `imatge` VARCHAR(45) NOT NULL,
  `preu` FLOAT NOT NULL,
  `categoria` INT NOT NULL,
  `comandes_idcomandes` INT NOT NULL,
  PRIMARY KEY (`idproductes`, `comandes_idcomandes`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `provincies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provincies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `provincies` (
  `idprovincies` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `clients_idclients` INT NOT NULL,
  PRIMARY KEY (`idprovincies`, `clients_idclients`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
